language: python

sudo: false

python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"

before_install:
   - pip install flake8

install:
   - python setup.py install

script:
   - python test.py
   - flake8 *.py
